### ISSUE TITLE
Alcalá, Espanha

### ISSUE THREAD

**Issue by Danielafsp** [joaquimrcarvalho/dehergne-locations#14]
**Nome do lugar / name of the place**
Alcalá, Espanha

**File  / Ficheiro**
vários

**Nome/id da pessoa / Name/id of the person**
n$Nicolás Gallardo/id=deh-nicolas-gallardo
n$Pedro Gómez/id=deh-pedro-gomez
n$Melchior Mora/id=deh-melchior-mora
n$Alonso Sanchéz/id=deh-alonso-sanchez
n$Spinellus/id=deh-spinellus

**Linha com o topónimo / line with the place**
-g.cli, linhas 95 & 750
-m.cli, linha 1669
-s.cli, linhas 210 & 1939

**Resultado de pesquisas feiras / Resultado of searches so far**

Há outras entradas com o local sendo Alcalá de Henares, mas estas dizem apenas Alcalá. Assumo, por isso, que não seja o mesmo sítio. Excepto, talvez, o Alonso Sanchéz, que entrou na ordem em Alcalá e a morte aponta para o seguinte: ls$morte/Alcalá de Henares# @wikidata:Q46940/15930527.

Uma pesquisa no google e na wikipedia mostra vários Alcalá em Espanha: https://pt.wikipedia.org/wiki/Alcal%C3%A1

**Comment by joaquimrcarvalho** [comment]
Como lugar de "entrada" é certamente Alcalá de Henares (https://www.wikidata.org/wiki/Q46940 ) onde existia um dos primeiros colégios jesuítas  ver https://www.uah.es/es/conoce-la-uah/la-universidad/edificios/Colegio-Maximos-Compania-de-Jesus.-Facultad-de-Derecho/
