### ISSUE TITLE
Tusculum, Itália

### ISSUE THREAD

**Issue by Danielafsp** [joaquimrcarvalho/dehergne-locations#19]
**Nome do lugar / name of the place**
Tusculum, Itália
**File  / Ficheiro**
dehergne-m.cli

**Nome/id da pessoa / Name/id of the person**
n$Antonio Saverio Morabito/id=deh-antonio-saverio-morabito

**Linha com o topónimo / line with the place**
1705 - ls$morte/Tusculum, Itália/17691031

**Resultado de pesquisas feiras / Resultado of searches so far**
Não será a antiga cidade de Túsculo. Poderá ser a cidade de Frascati, construida na zona dessa antiga cidade, que teve o nome de Tusculum Novum  em 1538, pelo papa Paulo III. (https://en.wikipedia.org/wiki/Frascati)

**Comment by joaquimrcarvalho** [comment]
Sim, os Jesuítas depois de extintos foram para Frascati que era conhecida como Tuscoli.

"'Villa Ruffinella (oggi chiamata Villa Tuscolana), vicino a
Frascati (in latino Tuscoli), sulla via Tuscolana per l
appunto, era stata acquistata dai gesuiti nel 1741."

Ver issue #10
