### ISSUE TITLE
Uguli, Bengala

### ISSUE THREAD

**Issue by Danielafsp** [joaquimrcarvalho/dehergne-locations#8]
**Nome do lugar / name of the place**
Uguli, Bengala

**File  / Ficheiro**
dehergne-d.cli

**Nome/id da pessoa / Name/id of the person**
n$Jacques Duchatz/id=deh-jacques-duchatz

**Linha com o topónimo / line with the place**
 ls$morte/Uguli, Bengala/16930400
linha 949

Se útil colocar algumas linhas de contexto / If usefull ad some lines for context
ls$estadia/Birmânia# @wikidata:Q836/16870000
ls$estadia/Inwa%Ava# @wikidata:Q2199759/16890000
ls$morte/Uguli, Bengala/16930400

**Resultado de pesquisas feitas / Resultado of searches so far**
Não encontro uma cidade com o nome "Uguli". Estou a assumir que se refere à cidade de Ugulim (Hugli), antigo território português, no Estado da bengala Ocidental. A página da Wikipédia para esta cidade, remete para a cidade de Chinsurah: https://www.wikidata.org/wiki/Q1006256.

A página da wikipédia em Inglês remete para uma diferente: https://www.wikidata.org/wiki/Q20099772.

Ambas têm coordenadas e a informação é semelhante. Coloco os dois códigos?

**Comment by joaquimrcarvalho** [comment]
Claramente há uma duplicação de informação na Wikidata, ambas as referências correspondem a "Uguli, Bengala".

Sugiro que se use https://www.wikidata.org/wiki/Q20099772 que tem a vantagem de incluir o nome "Hugli" o que não acontece com https://www.wikidata.org/wiki/Q1006256. Esta última pode ser referida entre parêntesis:

ls$morte/Uguli, Bengala# @wikipedia: Q20099772 (ou alternativamente Q1006256)/16930400
